### ISSUE TITLE
No module named 'jajapy.hmm'

### ISSUE THREAD

**Issue by lisandrojim** [Rapfff/jajapy#1]
Hello Rapfff,

I am curious to use your tool jajapy. I installed it on my machine and I get the following error:

`ModuleNotFoundError: No module named 'jajapy.hmm'`

Do you have an idea of what could it be?

**Comment by Rapfff** [comment]
Hi @lisandrojim,
Thank you for this feedback !
This problem should be solved by now. You can update _jajapy_ by running
`pip install jajapy -U`
or by reinstalling it
`
pip uninstall jajapy
pip install jajapy
`
Sorry for this
