### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by lisandrojim** [Rapfff/jajapy#3]
Thanks for updating the demo.py file! I am getting repeatedly the error below, is this normal? Maybe a simpler demo would work better? 

```
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
```

PS: If I may, it would be helpful to add a short description of the demo (e.g., a drawing of the markov model, the input parameters, outputs, and interpretation). I could provide this if I manage to run successfully the demo :-)

**Comment by Rapfff** [comment]
Mmm... Are you running it on a windows machine?

There is a better description of the demo in the documentation, [there](https://jajapy.readthedocs.io/en/latest/tuto.html#an-example-with-mc-random-restart) . But you're right, I should spend more time on documenting and commenting :-)

**Comment by Rapfff** [comment]
Could you give me what you get if you type `sys.platform` in a python terminal ?

**Comment by lisandrojim** [comment]
Hello Rapfff,

I get this:

import sys
sys.platform
Out[4]: ‘darwin’

And I am using a MacBook, not a windows machine. I will give a closer look at the documentation you provided in the link, it seems to be quite complete.

Kind regards,
Lisandro

_______________________________
Lisandro Jimenez, M.Sc. PDEng<https://people.utwente.nl/l.jimenezroa?tab=research>
PhD candidate in Computer Science
Formal Methods & Tools (FMT<https://www.utwente.nl/en/eemcs/fmt/>) group
PrimaVera<https://primavera-project.com> project
Faculty of Electrical Engineering, Mathematics and Computer Science (EEMCS)
University of Twente, The Netherlands
‭+31 53 489 15 60‬

On 15 Sep 2022, at 15:02, Rapfff ***@***.******@***.***>> wrote:



Could you give me what you get if you type sys.platform in a python terminal ?

**Comment by Rapfff** [comment]
Hi again!
You should not have this error anymore. But sadly I had removed multiprocessing for Mac OS.
Hence, I would recommend you to run it on a linux machine if you use it on fairly big dataset.
